/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLibrary;

/**
 *
 * @author Hicham
 */
public class EndPanel extends javax.swing.JPanel {
    private MainFrame frame;
    /**
     * Creates new form EndPanel
     */
    public EndPanel(MainFrame frame) {
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonReplay = new javax.swing.JButton();
        jButtonQuit = new javax.swing.JButton();

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTitle.setText("Thank you for playing !");

        jButtonReplay.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButtonReplay.setText("Play again");
        jButtonReplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReplayMouseClicked(evt);
            }
        });

        jButtonQuit.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButtonQuit.setText("Quit");
        jButtonQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonQuitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButtonReplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuit)
                    .addComponent(jButtonReplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQuitMouseClicked
        // TODO add your handling code here:
        this.frame.end();
    }//GEN-LAST:event_jButtonQuitMouseClicked

    private void jButtonReplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReplayMouseClicked
        // TODO add your handling code here:
        this.frame.playAgain();
    }//GEN-LAST:event_jButtonReplayMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JButton jButtonReplay;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
