/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLibrary;

/**
 *
 * @author Hicham
 */
public class PlayerPanel extends javax.swing.JPanel {
    private MainFrame frame;
    private int playerId;
    
    /**
     * Creates new form PlayerPanel
     * @param frame
     * @param playerId
     */
    public PlayerPanel(MainFrame frame, int playerId) {
        this.frame = frame;
        this.playerId = playerId;
        initComponents();
        this.jLabel1.setText("PlayerPanel number " + this.playerId + " works!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonLeaderboard = new javax.swing.JButton();

        jLabel1.setText("PlayerPanel works!");

        jButtonLeaderboard.setText("Display Leaderboard");
        jButtonLeaderboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLeaderboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLeaderboard)
                    .addComponent(jLabel1))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jButtonLeaderboard)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLeaderboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLeaderboardMouseClicked
        // TODO add your handling code here:
        this.frame.displayLeaderboard();
    }//GEN-LAST:event_jButtonLeaderboardMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLeaderboard;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
