/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLibrary;

import EnumLibrary.Action;
import EnumLibrary.Evolution;
import EnumLibrary.Resource;
import ModelLibrary.CardLibrary.Card;
import ModelLibrary.PlayerLibrary.Deck;
import ModelLibrary.PlayerLibrary.Player;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.util.EnumSet;
import javax.swing.DefaultListModel;
import javax.swing.Scrollable;
import javax.swing.SwingConstants;

/**
 *
 * @author Hicham, Aurélien
 */
public class PlayerPanel extends javax.swing.JPanel {
    private MainFrame frame;
    private int playerId;
    
    /**
     * Creates new form PlayerPanel
     * @param frame
     * @param playerId
     */
    public PlayerPanel(MainFrame frame, int playerId) {
        this.frame = frame;
        this.playerId = playerId;
        initComponents();
        this.jLabelPLayerId.setText("Player n° " + this.playerId);
        
        this.guiUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPLayerId = new javax.swing.JLabel();
        jButtonLeaderboard = new javax.swing.JButton();
        jScrollPaneCards = new javax.swing.JScrollPane();
        jListCards = new javax.swing.JList<>();
        jLabelDeck = new javax.swing.JLabel();
        jScrollPaneActions = new javax.swing.JScrollPane();
        jListAction = new javax.swing.JList<>();
        jLabelActions = new javax.swing.JLabel();
        jScrollPaneCardsPlayed = new javax.swing.JScrollPane();
        jListCardsPlayed = new javax.swing.JList<>();
        jLabelCardsPlayed = new javax.swing.JLabel();
        jLabelWonderName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonValidate = new javax.swing.JButton();
        jLabelCoins = new javax.swing.JLabel();
        jLabelCoinsValue = new javax.swing.JLabel();
        jLabelWonderEvolutionFirst = new javax.swing.JLabel();
        jLabelWonderEvolutionSecond = new javax.swing.JLabel();
        jLabelWonderEvolutionThird = new javax.swing.JLabel();
        jLabelCSName = new javax.swing.JLabel();
        jLabelCSValue = new javax.swing.JLabel();
        jLabelTMName = new javax.swing.JLabel();
        jLabelTMValue = new javax.swing.JLabel();
        jLabelCGName = new javax.swing.JLabel();
        jLabelCGValue = new javax.swing.JLabel();
        jLabelECName = new javax.swing.JLabel();
        jLabelECValue = new javax.swing.JLabel();
        jLabelStageName = new javax.swing.JLabel();
        jLabelStageValue = new javax.swing.JLabel();
        jLabelEntrepreunariatName = new javax.swing.JLabel();
        jLabelEntrepreunariatValue = new javax.swing.JLabel();
        jLabelProjetName = new javax.swing.JLabel();
        jLabelProjetValue = new javax.swing.JLabel();
        jLabelVictoryName = new javax.swing.JLabel();
        jLabelVictoryValue = new javax.swing.JLabel();
        jLabelKnowledgeName = new javax.swing.JLabel();
        jLabelKnowledgeValue = new javax.swing.JLabel();
        jLabelCentrifugeName = new javax.swing.JLabel();
        jLabelCentrifugeValue = new javax.swing.JLabel();
        jLabelPumpName = new javax.swing.JLabel();
        jLabelPumpValue = new javax.swing.JLabel();
        jLabelProoferName = new javax.swing.JLabel();
        jLabelProoferValue = new javax.swing.JLabel();

        jLabelPLayerId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPLayerId.setText("Player n° ID");

        jButtonLeaderboard.setText("Display Leaderboard");
        jButtonLeaderboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLeaderboardMouseClicked(evt);
            }
        });
        jButtonLeaderboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaderboardActionPerformed(evt);
            }
        });

        jListCards.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListCards.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListCards.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCardsValueChanged(evt);
            }
        });
        jScrollPaneCards.setViewportView(jListCards);

        jLabelDeck.setText("Deck");

        jListAction.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListAction.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListAction.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListActionValueChanged(evt);
            }
        });
        jScrollPaneActions.setViewportView(jListAction);

        jLabelActions.setText("Actions");

        jListCardsPlayed.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListCardsPlayed.setEnabled(false);
        jScrollPaneCardsPlayed.setViewportView(jListCardsPlayed);

        jLabelCardsPlayed.setText("Cards played");

        jLabelWonderName.setText("Wonder's Name");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonValidate.setText("Validate");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        jLabelCoins.setText("Coins : ");

        jLabelCoinsValue.setText("0");

        jLabelWonderEvolutionFirst.setText("First");

        jLabelWonderEvolutionSecond.setText("Second");

        jLabelWonderEvolutionThird.setText("Third");

        jLabelCSName.setText("CS : ");

        jLabelCSValue.setText("0");

        jLabelTMName.setText("TM : ");

        jLabelTMValue.setText("0");

        jLabelCGName.setText("CG : ");

        jLabelCGValue.setText("0");

        jLabelECName.setText("EC : ");

        jLabelECValue.setText("0");

        jLabelStageName.setText("Stage : ");

        jLabelStageValue.setText("0");

        jLabelEntrepreunariatName.setText("Entrep' : ");

        jLabelEntrepreunariatValue.setText("0");

        jLabelProjetName.setText("Projet : ");

        jLabelProjetValue.setText("0");

        jLabelVictoryName.setText("PV : ");

        jLabelVictoryValue.setText("0");

        jLabelKnowledgeName.setText("PM : ");

        jLabelKnowledgeValue.setText("0");

        jLabelCentrifugeName.setText("Centrifuge : ");

        jLabelCentrifugeValue.setText("0");

        jLabelPumpName.setText("Pump : ");

        jLabelPumpValue.setText("0");

        jLabelProoferName.setText("Proofer : ");

        jLabelProoferValue.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelWonderEvolutionFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelWonderEvolutionSecond)
                        .addGap(204, 204, 204)
                        .addComponent(jLabelWonderEvolutionThird)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLeaderboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPaneCardsPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelCentrifugeName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelCentrifugeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPumpName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPumpValue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelProoferName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelProoferValue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelProjetName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelProjetValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelStageName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelStageValue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelEntrepreunariatName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabelEntrepreunariatValue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jScrollPaneCards, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPaneActions, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelVictoryName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelVictoryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelKnowledgeName)
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabelKnowledgeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelWonderName)
                                .addGap(253, 253, 253))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelCardsPlayed)
                                .addGap(82, 82, 82)
                                .addComponent(jLabelDeck)
                                .addGap(87, 87, 87)
                                .addComponent(jLabelActions)
                                .addGap(45, 45, 45))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelCoins)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCoinsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCSName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCSValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTMName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTMValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jLabelCGName)
                                .addGap(3, 3, 3)
                                .addComponent(jLabelCGValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelECName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelECValue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPLayerId)))
                        .addGap(243, 243, 243))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPLayerId)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelECName)
                        .addComponent(jLabelECValue)
                        .addComponent(jLabelCGName)
                        .addComponent(jLabelCGValue))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTMName)
                        .addComponent(jLabelCSName)
                        .addComponent(jLabelCSValue))
                    .addComponent(jLabelTMValue))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEntrepreunariatName)
                                    .addComponent(jLabelEntrepreunariatValue)
                                    .addComponent(jLabelProjetName)
                                    .addComponent(jLabelProjetValue)
                                    .addComponent(jLabelStageName)
                                    .addComponent(jLabelStageValue)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCoinsValue)
                                    .addComponent(jLabelCoins))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCentrifugeName)
                            .addComponent(jLabelCentrifugeValue)
                            .addComponent(jLabelPumpName)
                            .addComponent(jLabelPumpValue)
                            .addComponent(jLabelProoferName)
                            .addComponent(jLabelProoferValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelKnowledgeName)
                            .addComponent(jLabelKnowledgeValue)
                            .addComponent(jLabelVictoryName)
                            .addComponent(jLabelVictoryValue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActions)
                    .addComponent(jLabelDeck)
                    .addComponent(jLabelCardsPlayed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneCards, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jScrollPaneActions, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonValidate))
                    .addComponent(jScrollPaneCardsPlayed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWonderName)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWonderEvolutionSecond)
                    .addComponent(jLabelWonderEvolutionThird)
                    .addComponent(jLabelWonderEvolutionFirst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLeaderboard)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLeaderboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLeaderboardMouseClicked
        // TODO add your handling code here:
        this.frame.displayLeaderboard();
    }//GEN-LAST:event_jButtonLeaderboardMouseClicked

    
    private void jListActionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListActionValueChanged
        Player player = this.frame.gameManager.getPlayer(this.playerId);
        // activer le bouton permettant de sélectionner une action
        /*if(this.jButtonSelectAction.isEnabled() == false && !player.getIsValidate()) {
            this.jButtonSelectAction.setEnabled(true);
        }*/
        
        // test si activation du bouton permettant de validation
        if(this.jButtonValidate.isEnabled() == false && !player.getIsValidate() && this.jListCards.hasFocus()) {
            this.jButtonValidate.setEnabled(true);
        }
    }//GEN-LAST:event_jListActionValueChanged

    private void jListCardsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCardsValueChanged
        Player player = this.frame.gameManager.getPlayer(this.playerId);
        // test si activation du bouton permettant de validation
        if(this.jButtonValidate.isEnabled() == false && !player.getIsValidate() && this.jListAction.hasFocus()) {
            this.jButtonValidate.setEnabled(true);
        }
    }//GEN-LAST:event_jListCardsValueChanged

    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
        // Désactivation du bouton
        this.jButtonValidate.setEnabled(false);
        // Désactivation des listes
        this.jListCards.setEnabled(false);
        this.jListAction.setEnabled(false);
        
        Player player = this.frame.gameManager.getPlayer(this.playerId);
        
        /* Select Card */
        // Récupération de la carte sélectionnée
        String nameCardSelected = this.jListCards.getSelectedValue();
        Card cardSelected = player.getCardDeckByName(nameCardSelected);
        // Sélection de la carte
        player.setCardSelected(cardSelected);
        this.frame.gameManager.setPlayer(player, this.playerId);
        /* Select Action */
        // Récupération de l'action sélectionnée
        Action actionSelected = Action.valueOf(this.jListAction.getSelectedValue());
        // Sélection de l'action
        player.setActionSelected(actionSelected);
        this.frame.gameManager.setPlayer(player, this.playerId);
        
        //Player player = this.frame.gameManager.getPlayer(this.playerId);
        player.setIsValidate(true);
        this.frame.gameManager.setPlayer(player, this.playerId);
        
        // On regarde si tous les joueurs ont validés 
        if(this.frame.gameManager.checkIfPlayersValidate() == true) {
            // On joue le tour
            this.frame.gameManager.playTurn();
            // GUI update
            this.frame.guiUpdatePlayersPanel();
        }
    }//GEN-LAST:event_jButtonValidateActionPerformed

    private void jButtonLeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaderboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLeaderboardActionPerformed

    // Permet de mettre fin à la partie
    public void end() {
        this.frame.endGame();
    }
    
    public void guiUpdate() {
        // On commence par vérifier si la partie est terminée
        if(this.frame.gameManager.getEndGame() == true) {
            this.end();
        }
        
        Player player = this.frame.gameManager.getPlayer(this.playerId);
        Deck deck = player.getDeck();
        Deck cardsPlayed = player.getCardsPlayed();
        
        player.getProductedRessources().forEach((productedRessource) -> {
            switch(productedRessource.getType()) {
                case CS:
                    this.jLabelCSValue.setText(Integer.toString(productedRessource.getValue()));
                    break;
                case TM:
                    this.jLabelTMValue.setText(Integer.toString(productedRessource.getValue()));
                    break;
                case CG:
                    this.jLabelCGValue.setText(Integer.toString(productedRessource.getValue()));
                    break;
                case EC:
                    this.jLabelECValue.setText(Integer.toString(productedRessource.getValue()));
                    break;
                case STAGE:
                    this.jLabelStageValue.setText(Integer.toString(productedRessource.getValue()));
                    break;
                case PROJET:
                    this.jLabelProjetValue.setText(Integer.toString(productedRessource.getValue()));
                    break;
                case ENTREPREUNARIAT:
                    this.jLabelEntrepreunariatValue.setText(Integer.toString(productedRessource.getValue()));
                    break;
            }
        });
        this.jLabelCoinsValue.setText(Integer.toString(player.getScore().getCoin().getValue()));
        this.jLabelVictoryValue.setText(Integer.toString(player.getScore().getTotalVictoryPoints().getValue()));
        this.jLabelKnowledgeValue.setText(Integer.toString(player.getScore().getKnowledge().getValue()));
        this.jLabelCentrifugeValue.setText(Integer.toString(player.getScore().getCentrifuge().getValue()));
        this.jLabelPumpValue.setText(Integer.toString(player.getScore().getPump().getValue()));
        this.jLabelProoferValue.setText(Integer.toString(player.getScore().getProofer().getValue()));
        
        this.jLabelWonderEvolutionFirst.setForeground(Color.black);
        this.jLabelWonderEvolutionSecond.setForeground(Color.black);
        this.jLabelWonderEvolutionThird.setForeground(Color.black);
        
        this.jLabelWonderName.setText(player.getGameBoard().getName().toString() + " - " + player.getGameBoard().getEvolution());
        this.jLabelWonderEvolutionFirst.setText("1.Cost:[");
        this.jLabelWonderEvolutionSecond.setText("2.Cost:[");
        this.jLabelWonderEvolutionThird.setText("3.Cost:[");
        player.getGameBoard().getSteps().get(0).getCost().forEach((cost) -> {
            this.jLabelWonderEvolutionFirst.setText(this.jLabelWonderEvolutionFirst.getText() + cost.getType() + " : " + cost.getValue() + " | ");
        });
        player.getGameBoard().getSteps().get(1).getCost().forEach((cost) -> {
            this.jLabelWonderEvolutionSecond.setText(this.jLabelWonderEvolutionSecond.getText() + cost.getType() + " : " + cost.getValue() + " | ");
        });
        player.getGameBoard().getSteps().get(2).getCost().forEach((cost) -> {
            this.jLabelWonderEvolutionThird.setText(this.jLabelWonderEvolutionThird.getText() + cost.getType() + " : " + cost.getValue() + " | ");
        });
        this.jLabelWonderEvolutionFirst.setText(this.jLabelWonderEvolutionFirst.getText() + "]");
        this.jLabelWonderEvolutionSecond.setText(this.jLabelWonderEvolutionSecond.getText() + "]");
        this.jLabelWonderEvolutionThird.setText(this.jLabelWonderEvolutionThird.getText() + "]");
        
        // Initialisation de la liste des cartes du deck
        DefaultListModel modelCards = new DefaultListModel();
        for(int i=0; i<deck.getListCards().size(); i++) {
            modelCards.addElement(deck.getListCards().get(i).getName());
        }
        this.jListCards.setModel(modelCards);
        // Initialisation de la liste des cartes jouées - A FINIR / VERIFIER !!
        DefaultListModel modelCardsPlayed = new DefaultListModel();
        for(int i=0; i<cardsPlayed.getListCards().size(); i++) {
            modelCardsPlayed.addElement(cardsPlayed.getListCards().get(i).getName());
        }
        this.jListCardsPlayed.setModel(modelCardsPlayed);
        // Initialisation de la liste des actions
        DefaultListModel modelActions = new DefaultListModel();
        EnumSet.allOf(Action.class).forEach(action -> modelActions.addElement(action.toString()));
        this.jListAction.setModel(modelActions);
        // Désactivation du bouton
        this.jButtonValidate.setEnabled(false);
        // Activation des listes
        this.jListCards.setEnabled(true);
        this.jListAction.setEnabled(true);
        // Affichage de l'âge 
        this.showAge(player.getGameBoard().getEvolution());
    }
    
    public void showAge(Evolution age) {
        if(null != age) switch (age) {
            case NONE:
                this.jLabelWonderEvolutionFirst.setForeground(Color.black);
                this.jLabelWonderEvolutionSecond.setForeground(Color.black);
                this.jLabelWonderEvolutionThird.setForeground(Color.black);
                break;
            case FIRST:
                this.jLabelWonderEvolutionFirst.setForeground(Color.green);
                this.jLabelWonderEvolutionSecond.setForeground(Color.black);
                this.jLabelWonderEvolutionThird.setForeground(Color.black);
                break;
            case SECOND:
                this.jLabelWonderEvolutionFirst.setForeground(Color.green);
                this.jLabelWonderEvolutionSecond.setForeground(Color.green);
                this.jLabelWonderEvolutionThird.setForeground(Color.black);
                break;
            case THIRD:
                this.jLabelWonderEvolutionFirst.setForeground(Color.green);
                this.jLabelWonderEvolutionSecond.setForeground(Color.green);
                this.jLabelWonderEvolutionThird.setForeground(Color.green);
                break;
            default:
                break;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLeaderboard;
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JLabel jLabelActions;
    private javax.swing.JLabel jLabelCGName;
    private javax.swing.JLabel jLabelCGValue;
    private javax.swing.JLabel jLabelCSName;
    private javax.swing.JLabel jLabelCSValue;
    private javax.swing.JLabel jLabelCardsPlayed;
    private javax.swing.JLabel jLabelCentrifugeName;
    private javax.swing.JLabel jLabelCentrifugeValue;
    private javax.swing.JLabel jLabelCoins;
    private javax.swing.JLabel jLabelCoinsValue;
    private javax.swing.JLabel jLabelDeck;
    private javax.swing.JLabel jLabelECName;
    private javax.swing.JLabel jLabelECValue;
    private javax.swing.JLabel jLabelEntrepreunariatName;
    private javax.swing.JLabel jLabelEntrepreunariatValue;
    private javax.swing.JLabel jLabelKnowledgeName;
    private javax.swing.JLabel jLabelKnowledgeValue;
    private javax.swing.JLabel jLabelPLayerId;
    private javax.swing.JLabel jLabelProjetName;
    private javax.swing.JLabel jLabelProjetValue;
    private javax.swing.JLabel jLabelProoferName;
    private javax.swing.JLabel jLabelProoferValue;
    private javax.swing.JLabel jLabelPumpName;
    private javax.swing.JLabel jLabelPumpValue;
    private javax.swing.JLabel jLabelStageName;
    private javax.swing.JLabel jLabelStageValue;
    private javax.swing.JLabel jLabelTMName;
    private javax.swing.JLabel jLabelTMValue;
    private javax.swing.JLabel jLabelVictoryName;
    private javax.swing.JLabel jLabelVictoryValue;
    private javax.swing.JLabel jLabelWonderEvolutionFirst;
    private javax.swing.JLabel jLabelWonderEvolutionSecond;
    private javax.swing.JLabel jLabelWonderEvolutionThird;
    private javax.swing.JLabel jLabelWonderName;
    private javax.swing.JList<String> jListAction;
    private javax.swing.JList<String> jListCards;
    private javax.swing.JList<String> jListCardsPlayed;
    private javax.swing.JScrollPane jScrollPaneActions;
    private javax.swing.JScrollPane jScrollPaneCards;
    private javax.swing.JScrollPane jScrollPaneCardsPlayed;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
